### PR TITLE
create dishlist

### PR DESCRIPTION
**Pull request by po4erk**
Connect to anywhere and transfer data as an array of objects

### CODE REVIEW

**Comment by iarickvigasi** [comment]
Dishlist не dash list)

**Comment by po4erk** [comment]
renamed)

**Comment by olbesp** [comment]
It looks nice. I've tried to render it inside the Restaurants screen on Pixel AVD.
I think the Counter component looks a little bit differently. Text colors inside of it are slightly different too, but this isn't a big problem for now. The Counter with a red arrow hasn't enough space. Maybe it'll look better if we decrease the image size. It will be better for small devices in portrait mode, but DishList component render the data correctly.
screenshot from 2018-06-02 12-37-48

**Comment by iarickvigasi** [comment]
We can merge only #20

**Pull request closed without merging**
